import { SimpleGit } from 'simple-git';
import { promises as fs } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import { logger } from '../utils/logger.js';
import { Receipt } from '../receipt/schema.js';
import { GitRepository } from './repo.js';
import { ReceiptFilter } from './types.js';

export class MetadataBranchManager {
  private repo: GitRepository;
  private git: SimpleGit;
  private branchName: string;

  constructor(repo: GitRepository) {
    this.repo = repo;
    this.git = repo.getGitInstance();
    this.branchName = repo.getMetadataBranchName();
  }

  /**
   * Executes a raw git command safely
   */
  private execGit(command: string, input?: string): string {
    const cwd = this.repo.getRepoPath();
    try {
      if (input) {
        return execSync(command, { cwd, input, encoding: 'utf8' });
      }
      return execSync(command, { cwd, encoding: 'utf8' });
    } catch (error: any) {
      throw new Error(`Git command failed: ${error.message}`);
    }
  }

  /**
   * Initializes the metadata branch using Git worktree (safer approach)
   */
  async initialize(): Promise<void> {
    try {
      // Check if branch already exists
      if (await this.repo.branchExists(this.branchName)) {
        logger.warn(
          `Metadata branch '${this.branchName}' already exists. Skipping initialization.`
        );
        return;
      }

      logger.info(`Creating metadata branch: ${this.branchName}`);

      // Check if repository is empty
      const isEmpty = await this.repo.isEmptyRepository();
      let originalBranch = '';
      let hadChanges = false;

      if (!isEmpty) {
        // Save current branch and check for uncommitted changes
        originalBranch = await this.repo.getCurrentBranch();
        const status = await this.git.status();

        if (status.modified.length > 0 || status.not_added.length > 0) {
          hadChanges = true;
          // Stash changes
          await this.git.stash(['push', '-u', '-m', 'commitledger-temp-stash']);
        }
      }

      try {
        // Create orphan branch (no parent commits)
        await this.git.checkout(['--orphan', this.branchName]);

        // Remove all files from staging
        try {
          await this.git.raw(['rm', '-rf', '.']);
        } catch {
          // Ignore error if no files to remove (empty repo)
        }

        // Create checkpoints directory and a README
        const repoPath = this.repo.getRepoPath();
        const checkpointsDir = join(repoPath, 'checkpoints');
        await fs.mkdir(checkpointsDir, { recursive: true });
        await fs.writeFile(join(checkpointsDir, '.gitkeep'), '', 'utf8');

        const readmeContent = `# AI Commit Ledger - Metadata Branch

This branch stores AI receipts for commits in your repository.

**Do not manually edit files in this branch.**

Each commit receipt is stored as \`checkpoints/<sha>.json\`.

Generated by: commitLedger
Version: 1.0
`;

        await fs.writeFile(join(repoPath, 'README.md'), readmeContent, 'utf8');

        // Make initial commit
        await this.git.add('.');
        await this.git.commit('Initialize AI Commit Ledger metadata branch');

        logger.success(`Metadata branch '${this.branchName}' created`);

        // Switch back to original branch (only if repo wasn't empty)
        if (!isEmpty && originalBranch) {
          await this.git.checkout(originalBranch);

          // Restore stashed changes if any
          if (hadChanges) {
            try {
              await this.git.stash(['pop']);
            } catch {
              logger.warn('Could not restore stashed changes automatically');
            }
          }
        } else {
          // For empty repos, create and switch to main branch for user to work
          const defaultBranch = 'main';
          try {
            // Check out an orphan branch for the user's work
            await this.git.checkout(['--orphan', defaultBranch]);
            // Clear any files that might have been copied
            try {
              await this.git.raw(['rm', '-rf', '.']);
            } catch {
              // Ignore - directory might already be empty
            }
            logger.info(
              `Switched to '${defaultBranch}' branch. You can now make commits as usual.`
            );
          } catch (error) {
            logger.warn(
              `Could not switch to ${defaultBranch}: ${error}. Run 'git checkout --orphan ${defaultBranch}' manually.`
            );
          }
        }
      } catch (error) {
        // Try to recover
        if (!isEmpty && originalBranch) {
          try {
            await this.git.checkout(originalBranch);
          } catch {}
        }
        throw error;
      }
    } catch (error) {
      throw new Error(`Failed to initialize metadata branch: ${error}`);
    }
  }

  /**
   * Stores a receipt in the metadata branch
   */
  async storeReceipt(sha: string, receipt: Receipt): Promise<void> {
    try {
      const receiptContent = JSON.stringify(receipt, null, 2);
      const receiptFileName = `${sha}.json`;

      // Use Git plumbing to avoid checkout
      // 1. Create blob for receipt
      const blobHash = this.execGit(`git hash-object -w --stdin`, receiptContent).trim();

      // 2. Get current commit from metadata branch
      const currentCommit = this.execGit(`git rev-parse refs/heads/${this.branchName}`).trim();

      // 3. Get the checkpoints tree
      let checkpointsTreeHash = '';
      try {
        const treeOutput = this.execGit(`git ls-tree ${currentCommit} checkpoints`);
        const match = treeOutput.match(/tree\s+([a-f0-9]+)/);
        checkpointsTreeHash = match ? match[1] : '';
      } catch {
        // checkpoints tree doesn't exist yet
      }

      // 4. Get existing files in checkpoints
      let existingFiles = '';
      if (checkpointsTreeHash) {
        try {
          existingFiles = this.execGit(`git ls-tree ${checkpointsTreeHash}`);
        } catch {
          // Empty tree
        }
      }

      // 5. Build new tree with the receipt
      const existingEntries = existingFiles
        .split('\n')
        .filter((line) => line && !line.includes(receiptFileName) && !line.includes('.gitkeep'));

      const newTreeContent = [
        ...existingEntries,
        `100644 blob ${blobHash}\t${receiptFileName}`,
      ]
        .filter(Boolean)
        .join('\n') + '\n';

      const newCheckpointsTree = this.execGit('git mktree', newTreeContent).trim();

      // 6. Get README hash
      let readmeHash = '';
      try {
        const readmeOutput = this.execGit(`git ls-tree ${currentCommit} README.md`);
        const match = readmeOutput.match(/blob\s+([a-f0-9]+)/);
        readmeHash = match ? match[1] : '';
      } catch {
        // No README
      }

      // 7. Create root tree
      const rootTreeContent = [
        readmeHash ? `100644 blob ${readmeHash}\tREADME.md` : '',
        `040000 tree ${newCheckpointsTree}\tcheckpoints`,
      ]
        .filter(Boolean)
        .join('\n') + '\n';

      const rootTreeHash = this.execGit('git mktree', rootTreeContent).trim();

      // 8. Create new commit
      const commitMessage = `Add AI receipt for commit ${sha}`;
      const newCommitHash = this.execGit(
        `git commit-tree ${rootTreeHash} -p ${currentCommit} -m "${commitMessage}"`
      ).trim();

      // 9. Update branch reference
      this.execGit(`git update-ref refs/heads/${this.branchName} ${newCommitHash}`);

      logger.debug(`Stored receipt for ${sha} in metadata branch`);
    } catch (error) {
      throw new Error(`Failed to store receipt for ${sha}: ${error}`);
    }
  }

  /**
   * Retrieves a receipt from the metadata branch
   */
  async retrieveReceipt(sha: string): Promise<Receipt | null> {
    try {
      // Try full SHA first
      let receiptPath = `checkpoints/${sha}.json`;
      try {
        const content = await this.git.show([
          `${this.branchName}:${receiptPath}`,
        ]);
        if (content) {
          return JSON.parse(content) as Receipt;
        }
      } catch {
        // If full SHA fails, try to find by short SHA prefix
        const files = await this.listReceiptFiles();
        const matchingFile = files.find((f) => f.startsWith(sha));
        if (matchingFile) {
          receiptPath = `checkpoints/${matchingFile}`;
          const content = await this.git.show([
            `${this.branchName}:${receiptPath}`,
          ]);
          return JSON.parse(content) as Receipt;
        }
      }
      return null;
    } catch (error) {
      logger.debug(`Receipt not found for ${sha}: ${error}`);
      return null;
    }
  }

  /**
   * Lists all receipt files in the metadata branch
   */
  private async listReceiptFiles(): Promise<string[]> {
    try {
      const output = this.execGit(
        `git ls-tree --name-only ${this.branchName}:checkpoints`
      );
      return output.split('\n').filter((f) => f.endsWith('.json'));
    } catch {
      return [];
    }
  }

  /**
   * Lists all receipts in the metadata branch
   */
  async listReceipts(filter?: ReceiptFilter): Promise<Receipt[]> {
    try {
      const files = await this.listReceiptFiles();
      const receipts: Receipt[] = [];

      for (const file of files) {
        const sha = file.replace('.json', '');
        const receipt = await this.retrieveReceipt(sha);

        if (!receipt) continue;

        // Apply filters
        if (filter) {
          if (filter.sha && !receipt.commit_metadata.sha.startsWith(filter.sha)) {
            continue;
          }
          if (
            filter.branch &&
            receipt.commit_metadata.branch !== filter.branch
          ) {
            continue;
          }
          if (
            filter.author &&
            receipt.commit_metadata.author !== filter.author
          ) {
            continue;
          }
          if (
            filter.agentType &&
            receipt.agent_metadata?.agent_type !== filter.agentType
          ) {
            continue;
          }
          if (
            filter.dateFrom &&
            new Date(receipt.commit_metadata.timestamp) < filter.dateFrom
          ) {
            continue;
          }
          if (
            filter.dateTo &&
            new Date(receipt.commit_metadata.timestamp) > filter.dateTo
          ) {
            continue;
          }
          if (
            filter.minConfidence !== undefined &&
            receipt.agent_metadata &&
            receipt.agent_metadata.confidence_score < filter.minConfidence
          ) {
            continue;
          }
        }

        receipts.push(receipt);
      }

      // Sort by timestamp (newest first)
      receipts.sort(
        (a, b) =>
          new Date(b.commit_metadata.timestamp).getTime() -
          new Date(a.commit_metadata.timestamp).getTime()
      );

      return receipts;
    } catch (error) {
      logger.error(`Failed to list receipts: ${error}`);
      return [];
    }
  }

  /**
   * Checks if a receipt exists for a given commit SHA
   */
  async receiptExists(sha: string): Promise<boolean> {
    const receipt = await this.retrieveReceipt(sha);
    return receipt !== null;
  }

  /**
   * Deletes a receipt from the metadata branch
   */
  async deleteReceipt(sha: string): Promise<void> {
    try {
      const currentCommit = this.execGit(`git rev-parse refs/heads/${this.branchName}`).trim();

      const tree = this.execGit(`git ls-tree ${currentCommit} checkpoints`);
      const match = tree.match(/tree\s+([a-f0-9]+)/);
      if (!match) throw new Error('Checkpoints tree not found');

      const checkpointsTreeHash = match[1];

      const existingFiles = this.execGit(`git ls-tree ${checkpointsTreeHash}`);
      const newTreeContent = existingFiles
        .split('\n')
        .filter((line) => line && !line.includes(`${sha}.json`))
        .join('\n') + '\n';

      const newCheckpointsTree = this.execGit('git mktree', newTreeContent).trim();

      const readme = this.execGit(`git ls-tree ${currentCommit} README.md`);
      const readmeMatch = readme.match(/blob\s+([a-f0-9]+)/);
      const readmeHash = readmeMatch ? readmeMatch[1] : '';

      const rootTreeContent =
        `100644 blob ${readmeHash}\tREADME.md\n` +
        `040000 tree ${newCheckpointsTree}\tcheckpoints\n`;

      const rootTreeHash = this.execGit('git mktree', rootTreeContent).trim();

      const newCommitHash = this.execGit(
        `git commit-tree ${rootTreeHash} -p ${currentCommit} -m "Remove AI receipt for commit ${sha}"`
      ).trim();

      this.execGit(`git update-ref refs/heads/${this.branchName} ${newCommitHash}`);

      logger.debug(`Deleted receipt for ${sha}`);
    } catch (error) {
      throw new Error(`Failed to delete receipt for ${sha}: ${error}`);
    }
  }
}
