import { SimpleGit } from 'simple-git';
import { promises as fs } from 'fs';
import { join } from 'path';
import { logger } from '../utils/logger.js';
import { Receipt } from '../receipt/schema.js';
import { GitRepository } from './repo.js';
import { ReceiptFilter } from './types.js';

export class MetadataBranchManager {
  private repo: GitRepository;
  private git: SimpleGit;
  private branchName: string;

  constructor(repo: GitRepository) {
    this.repo = repo;
    this.git = repo.getGitInstance();
    this.branchName = repo.getMetadataBranchName();
  }

  /**
   * Initializes the metadata branch (orphan branch with no history)
   */
  async initialize(): Promise<void> {
    try {
      // Check if branch already exists
      if (await this.repo.branchExists(this.branchName)) {
        logger.warn(
          `Metadata branch '${this.branchName}' already exists. Skipping initialization.`
        );
        return;
      }

      logger.info(`Creating metadata branch: ${this.branchName}`);

      // Save current branch
      const originalBranch = await this.repo.getCurrentBranch();

      // Create orphan branch (no parent commits)
      await this.git.checkout(['--orphan', this.branchName]);

      // Remove all files from staging (orphan branch starts with all files staged)
      await this.git.raw(['rm', '-rf', '.']);

      // Create checkpoints directory and a README
      const repoPath = this.repo.getRepoPath();
      const checkpointsDir = join(repoPath, 'checkpoints');
      await fs.mkdir(checkpointsDir, { recursive: true });

      const readmeContent = `# AI Commit Ledger - Metadata Branch

This branch stores AI receipts for commits in your repository.

**Do not manually edit files in this branch.**

Each commit receipt is stored as \`checkpoints/<sha>.json\`.

Generated by: commitLedger
Version: 1.0
`;

      await fs.writeFile(join(repoPath, 'README.md'), readmeContent, 'utf8');

      // Make initial commit
      await this.git.add('.');
      await this.git.commit('Initialize AI Commit Ledger metadata branch');

      logger.success(`Metadata branch '${this.branchName}' created`);

      // Switch back to original branch
      await this.git.checkout(originalBranch);
    } catch (error) {
      throw new Error(`Failed to initialize metadata branch: ${error}`);
    }
  }

  /**
   * Stores a receipt in the metadata branch
   */
  async storeReceipt(sha: string, receipt: Receipt): Promise<void> {
    try {
      // Save current branch
      const originalBranch = await this.repo.getCurrentBranch();

      // Switch to metadata branch
      await this.git.checkout(this.branchName);

      // Write receipt to file
      const repoPath = this.repo.getRepoPath();
      const checkpointsDir = join(repoPath, 'checkpoints');
      await fs.mkdir(checkpointsDir, { recursive: true });

      const receiptPath = join(checkpointsDir, `${sha}.json`);
      await fs.writeFile(receiptPath, JSON.stringify(receipt, null, 2), 'utf8');

      // Commit the receipt
      await this.git.add(receiptPath);
      await this.git.commit(`Add AI receipt for commit ${sha}`);

      logger.debug(`Stored receipt for ${sha} in metadata branch`);

      // Switch back to original branch
      await this.git.checkout(originalBranch);
    } catch (error) {
      throw new Error(`Failed to store receipt for ${sha}: ${error}`);
    }
  }

  /**
   * Retrieves a receipt from the metadata branch
   */
  async retrieveReceipt(sha: string): Promise<Receipt | null> {
    try {
      // Use git show to read file from metadata branch without checking it out
      const receiptPath = `checkpoints/${sha}.json`;
      const content = await this.git.show([
        `${this.branchName}:${receiptPath}`,
      ]);

      if (!content) {
        return null;
      }

      const receipt = JSON.parse(content) as Receipt;
      return receipt;
    } catch (error) {
      logger.debug(`Receipt not found for ${sha}: ${error}`);
      return null;
    }
  }

  /**
   * Lists all receipts in the metadata branch
   */
  async listReceipts(filter?: ReceiptFilter): Promise<Receipt[]> {
    try {
      // Save current branch
      const originalBranch = await this.repo.getCurrentBranch();

      // Switch to metadata branch temporarily to read files
      await this.git.checkout(this.branchName);

      const repoPath = this.repo.getRepoPath();
      const checkpointsDir = join(repoPath, 'checkpoints');

      // Read all receipt files
      const files = await fs.readdir(checkpointsDir);
      const receiptFiles = files.filter((f) => f.endsWith('.json'));

      const receipts: Receipt[] = [];

      for (const file of receiptFiles) {
        const content = await fs.readFile(
          join(checkpointsDir, file),
          'utf8'
        );
        const receipt = JSON.parse(content) as Receipt;

        // Apply filters
        if (filter) {
          if (filter.sha && receipt.commit_metadata.sha !== filter.sha) {
            continue;
          }
          if (
            filter.branch &&
            receipt.commit_metadata.branch !== filter.branch
          ) {
            continue;
          }
          if (
            filter.author &&
            receipt.commit_metadata.author !== filter.author
          ) {
            continue;
          }
          if (
            filter.agentType &&
            receipt.agent_metadata?.agent_type !== filter.agentType
          ) {
            continue;
          }
          if (
            filter.dateFrom &&
            new Date(receipt.commit_metadata.timestamp) < filter.dateFrom
          ) {
            continue;
          }
          if (
            filter.dateTo &&
            new Date(receipt.commit_metadata.timestamp) > filter.dateTo
          ) {
            continue;
          }
          if (
            filter.minConfidence !== undefined &&
            receipt.agent_metadata &&
            receipt.agent_metadata.confidence_score < filter.minConfidence
          ) {
            continue;
          }
        }

        receipts.push(receipt);
      }

      // Switch back to original branch
      await this.git.checkout(originalBranch);

      // Sort by timestamp (newest first)
      receipts.sort(
        (a, b) =>
          new Date(b.commit_metadata.timestamp).getTime() -
          new Date(a.commit_metadata.timestamp).getTime()
      );

      return receipts;
    } catch (error) {
      logger.error(`Failed to list receipts: ${error}`);
      return [];
    }
  }

  /**
   * Checks if a receipt exists for a given commit SHA
   */
  async receiptExists(sha: string): Promise<boolean> {
    const receipt = await this.retrieveReceipt(sha);
    return receipt !== null;
  }

  /**
   * Deletes a receipt from the metadata branch
   */
  async deleteReceipt(sha: string): Promise<void> {
    try {
      // Save current branch
      const originalBranch = await this.repo.getCurrentBranch();

      // Switch to metadata branch
      await this.git.checkout(this.branchName);

      // Delete receipt file
      const repoPath = this.repo.getRepoPath();
      const receiptPath = join(repoPath, 'checkpoints', `${sha}.json`);
      await fs.unlink(receiptPath);

      // Commit the deletion
      await this.git.add(receiptPath);
      await this.git.commit(`Remove AI receipt for commit ${sha}`);

      logger.debug(`Deleted receipt for ${sha}`);

      // Switch back to original branch
      await this.git.checkout(originalBranch);
    } catch (error) {
      throw new Error(`Failed to delete receipt for ${sha}: ${error}`);
    }
  }
}
